# Generated by Django 4.1 on 2022-08-24 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ferdolt', '0011_remove_message_file_remove_message_recipient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_made', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('size', models.FloatField(null=True)),
                ('is_deleted', models.BooleanField()),
                ('last_modified_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Synchronization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_received', models.DateTimeField(auto_now_add=True)),
                ('time_applied', models.DateTimeField()),
                ('is_applied', models.BooleanField(default=False)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flux.file')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ferdolt.server')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_sent', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flux.file')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferdolt.server')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractionDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferdolt.database')),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flux.extraction')),
            ],
        ),
        migrations.AddField(
            model_name='extraction',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flux.file'),
        ),
    ]
