# Generated by Django 4.1 on 2022-08-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraction',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
