# Generated by Django 4.1 on 2022-08-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0002_extraction_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraction',
            name='time_made',
            field=models.DateTimeField(),
        ),
    ]
