# Generated by Django 4.1 on 2022-08-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0003_alter_extraction_time_made'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='extractions'),
        ),
        migrations.AlterField(
            model_name='file',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
