# Generated by Django 4.1 on 2022-08-30 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ferdolt', '0012_alter_table_options_column_is_nullable'),
        ('flux', '0004_alter_file_file_alter_file_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='SynchronizationDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferdolt.database')),
                ('synchronization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flux.synchronization')),
            ],
        ),
    ]
