# Generated by Django 4.1 on 2022-09-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0006_encrypt_previously_generated_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='hash',
            field=models.TextField(blank=True, null=True),
        ),
    ]
