# Generated by Django 4.1 on 2022-09-08 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ferdolt', '0020_encrypt_database_connection_credentials'),
        ('flux', '0010_alter_synchronizationdatabase_is_synchronized'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionDatabaseSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraction_database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flux.extractiondatabase')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferdolt.databaseschema')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractionTargetDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferdolt.database')),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flux.extraction')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraction_database_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flux.extractiondatabaseschema')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferdolt.table')),
            ],
        ),
    ]
