# Generated by Django 4.1 on 2022-09-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0011_extractiondatabaseschema_extractiontargetdatabase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractiontargetdatabase',
            name='is_applied',
            field=models.BooleanField(default=False),
        ),
    ]
