# Generated by Django 4.1 on 2022-09-08 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ferdolt', '0020_encrypt_database_connection_credentials'),
        ('flux', '0012_extractiontargetdatabase_is_applied'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExtractionDatabase',
            new_name='ExtractionSourceDatabase',
        ),
        migrations.RenameModel(
            old_name='ExtractionTable',
            new_name='ExtractionSourceDatabaseSchema',
        ),
        migrations.RenameModel(
            old_name='ExtractionDatabaseSchema',
            new_name='ExtractionSourceTable',
        ),
        migrations.RemoveField(
            model_name='extractionsourcedatabaseschema',
            name='extraction_database_schema',
        ),
        migrations.RemoveField(
            model_name='extractionsourcedatabaseschema',
            name='table',
        ),
        migrations.RemoveField(
            model_name='extractionsourcetable',
            name='extraction_database',
        ),
        migrations.RemoveField(
            model_name='extractionsourcetable',
            name='schema',
        ),
        migrations.AddField(
            model_name='extractionsourcedatabaseschema',
            name='extraction_database',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flux.extractionsourcedatabase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extractionsourcedatabaseschema',
            name='schema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ferdolt.databaseschema'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extractionsourcetable',
            name='extraction_database_schema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flux.extractionsourcedatabaseschema'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extractionsourcetable',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ferdolt.table'),
            preserve_default=False,
        ),
    ]
