# Generated by Django 4.1 on 2022-09-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0013_rename_extractiondatabase_extractionsourcedatabase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractiontargetdatabase',
            name='time_applied',
            field=models.DateTimeField(null=True),
        ),
    ]
