# Generated by Django 4.1 on 2022-09-20 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('ferdolt', '0025_alter_database_port_alter_historicaldatabase_port'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flux', '0017_extraction_end_time_historicalextraction_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalExtractionTargetDatabaseTable',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('time_made', models.DateTimeField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('extraction_target_database', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='flux.extractiontargetdatabase')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ferdolt.table')),
            ],
            options={
                'verbose_name': 'historical extraction target database table',
                'verbose_name_plural': 'historical extraction target database tables',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ExtractionTargetDatabaseTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_made', models.DateTimeField(null=True)),
                ('extraction_target_database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flux.extractiontargetdatabase')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferdolt.table')),
            ],
        ),
    ]
