# Generated by Django 4.1 on 2022-08-22 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data_type', models.CharField(max_length=50)),
                ('datetime_precision', models.IntegerField(null=True)),
                ('character_maximum_length', models.IntegerField(null=True)),
                ('numeric_precision', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Column',
                'verbose_name_plural': 'Columns',
            },
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=150)),
                ('password', models.TextField()),
            ],
            options={
                'verbose_name': 'Database',
                'verbose_name_plural': 'Databases',
            },
        ),
        migrations.CreateModel(
            name='DatabaseManagementSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Database management system',
                'verbose_name_plural': 'Database management systems',
            },
        ),
        migrations.CreateModel(
            name='DatabaseSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferdolt.database')),
            ],
            options={
                'verbose_name': 'Database schema',
                'verbose_name_plural': 'Database schemas',
                'unique_together': {('database', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferdolt.databaseschema')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'unique_together': {('schema', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DatabaseManagementSystemVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=25)),
                ('dbms', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ferdolt.databasemanagementsystem')),
            ],
            options={
                'verbose_name': 'Database management system version',
                'verbose_name_plural': 'Database management system versions',
            },
        ),
        migrations.AddField(
            model_name='database',
            name='dbms_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ferdolt.databasemanagementsystemversion'),
        ),
        migrations.CreateModel(
            name='ColumnConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary_key', models.BooleanField(default=False)),
                ('is_foreign_key', models.BooleanField(default=False)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferdolt.column')),
            ],
        ),
        migrations.AddField(
            model_name='column',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferdolt.table'),
        ),
        migrations.AlterUniqueTogether(
            name='database',
            unique_together={('dbms_version', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='column',
            unique_together={('table', 'name')},
        ),
    ]
