# Generated by Django 4.1 on 2022-10-11 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ferdolt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnconstraint',
            name='references_tracking_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='references_tracking_id', to='ferdolt.column'),
        ),
        migrations.AddField(
            model_name='historicalcolumnconstraint',
            name='references_tracking_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ferdolt.column'),
        ),
    ]
