# Generated by Django 4.1 on 2022-08-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferdolt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='instance_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
