# Generated by Django 4.1 on 2022-08-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferdolt', '0002_database_instance_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='host',
            field=models.CharField(default='localhost', max_length=150),
        ),
        migrations.AddField(
            model_name='database',
            name='port',
            field=models.IntegerField(default=1433),
        ),
    ]
