# Generated by Django 4.1 on 2022-10-12 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ferdolt', '0002_columnconstraint_references_tracking_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ferdolt.server'),
        ),
        migrations.AddField(
            model_name='historicaldatabase',
            name='server',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ferdolt.server'),
        ),
        migrations.AlterField(
            model_name='historicalserver',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
