# Generated by Django 4.1.3 on 2022-11-14 15:31

from django.db import migrations, models
import django.db.models.deletion
import ferdolt.models


class Migration(migrations.Migration):

    dependencies = [
        ('ferdolt', '0007_create_default_dbms_versions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateServerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_made', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(default=ferdolt.models.generate_random_string, max_length=10, unique=True)),
                ('is_accepted', models.BooleanField(null=True)),
                ('server_created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ferdolt.server')),
            ],
        ),
    ]
