# Generated by Django 4.1 on 2022-08-24 10:17

from django.db import migrations, models
import ferdolt.models


class Migration(migrations.Migration):

    dependencies = [
        ('ferdolt', '0007_auto_20220824_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='server_id',
            field=models.CharField(default=ferdolt.models.generate_server_id, max_length=15, unique=True),
        ),
    ]
