# Generated by Django 4.1.3 on 2022-11-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferdolt', '0009_createserverrequest_fernet_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalserver',
            name='host',
            field=models.CharField(default='localhost', max_length=255),
        ),
        migrations.AddField(
            model_name='server',
            name='host',
            field=models.CharField(default='localhost', max_length=255),
        ),
    ]
