# Generated by Django 4.1 on 2022-08-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferdolt', '0011_remove_message_file_remove_message_recipient_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['schema__database__name', 'schema__name', 'name'], 'verbose_name': 'Table', 'verbose_name_plural': 'Tables'},
        ),
        migrations.AddField(
            model_name='column',
            name='is_nullable',
            field=models.BooleanField(default=True),
        ),
    ]
