# Generated by Django 4.1 on 2022-08-30 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ferdolt', '0012_alter_table_options_column_is_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnconstraint',
            name='references',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='references', to='ferdolt.column'),
        ),
    ]
