# Generated by Django 4.1 on 2022-08-30 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ferdolt', '0014_set_columnconstraint_references'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ['table__schema__database__name', 'table__schema__name', 'table__name', 'name'], 'verbose_name': 'Column', 'verbose_name_plural': 'Columns'},
        ),
        migrations.AlterModelOptions(
            name='columnconstraint',
            options={'ordering': ['column__table__schema__database__name', 'column__table__schema__name', 'column__table__name', 'column__name', 'is_primary_key', 'is_foreign_key']},
        ),
        migrations.AddField(
            model_name='table',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='column',
            name='character_maximum_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='column',
            name='datetime_precision',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='column',
            name='numeric_precision',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='columnconstraint',
            name='references',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='references', to='ferdolt.column'),
        ),
        migrations.AlterField(
            model_name='database',
            name='instance_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
