# Generated by Django 4.1 on 2022-08-31 12:55

from django.db import migrations

def set_model_names_to_lower_case(apps, schema_editor):
    models = [
        apps.get_model("ferdolt", "Column"),
        apps.get_model("ferdolt", "Table"),
        apps.get_model("ferdolt", "DatabaseSchema"),
        apps.get_model("ferdolt", "Database")
    ]

    for model in models:
        for record in model.objects.all():
            record.name = record.name.lower()
            record.save()

class Migration(migrations.Migration):

    dependencies = [
        ('ferdolt', '0016_set_table_levels'),
    ]

    operations = [
        migrations.RunPython( set_model_names_to_lower_case, reverse_code=migrations.RunPython.noop )
    ]
