# Generated by Django 4.1 on 2022-09-07 07:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ferdolt', '0017_modify_database_schema_table_and_column_names_to_lowercase'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='time_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
