# Generated by Django 4.1 on 2022-09-07 09:33

from cryptography.fernet import Fernet

from django.db import migrations

from core.functions import encrypt
from ferdolt_web.settings import FERNET_KEY

def encrypt_database_connection_parameters(apps, schema_editor):
    Database = apps.get_model("ferdolt", "Database")

    for database in Database.objects.all():
        database.username = encrypt(database.username)[1]
        database.host = encrypt(database.host)[1]
        database.password = encrypt(database.password)[1]
        database.port = encrypt(database.port)[1]
        
        database.save()

class Migration(migrations.Migration):

    dependencies = [
        ('ferdolt', '0019_alter_database_port'),
    ]

    operations = [
        migrations.RunPython(encrypt_database_connection_parameters, 
        reverse_code=migrations.RunPython.noop)
    ]
