# Generated by Django 4.1 on 2022-09-09 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ferdolt', '0020_encrypt_database_connection_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='deletion_table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ferdolt.table'),
        ),
    ]
