# Generated by Django 4.1 on 2022-09-09 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ferdolt', '0021_table_deletion_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='deletion_table',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ferdolt.table'),
        ),
    ]
