# Generated by Django 4.1 on 2022-09-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferdolt', '0023_alter_table_deletion_table_historicaltable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='is_initialized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='database',
            name='provides_successful_connection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaldatabase',
            name='is_initialized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaldatabase',
            name='provides_successful_connection',
            field=models.BooleanField(default=False),
        ),
    ]
