# Generated by Django 4.1 on 2022-09-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferdolt', '0024_database_is_initialized_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='port',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='historicaldatabase',
            name='port',
            field=models.TextField(),
        ),
    ]
