# Generated by Django 4.1 on 2022-08-22 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ferdolt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ferdolt.table')),
            ],
            options={
                'verbose_name': 'Group table',
                'verbose_name_plural': 'Group tables',
            },
        ),
        migrations.CreateModel(
            name='GroupDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_writeable', models.BooleanField(default=True)),
                ('is_readable', models.BooleanField(default=True)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ferdolt.database')),
            ],
            options={
                'verbose_name': 'Group database',
                'verbose_name_plural': 'Group databases',
            },
        ),
        migrations.CreateModel(
            name='GroupColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_required', models.BooleanField(default=False)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ferdolt.column')),
                ('group_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.grouptable')),
            ],
        ),
    ]
