# Generated by Django 4.1 on 2022-09-02 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ferdolt', '0017_modify_database_schema_table_and_column_names_to_lowercase'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='groupdatabase',
            name='name',
        ),
        migrations.AlterField(
            model_name='groupcolumn',
            name='column',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ferdolt.column'),
        ),
        migrations.AlterField(
            model_name='groupdatabase',
            name='database',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ferdolt.database'),
        ),
        migrations.AlterField(
            model_name='grouptable',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ferdolt.table'),
        ),
        migrations.CreateModel(
            name='GroupColumnConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_unique', models.BooleanField(default=False)),
                ('is_foreign_key', models.BooleanField(default=False)),
                ('is_primary_key', models.BooleanField(default=False)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.groupcolumn')),
                ('references', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='references', to='groups.groupcolumn')),
            ],
        ),
        migrations.AddField(
            model_name='groupdatabase',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='groups.group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grouptable',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='groups.group'),
            preserve_default=False,
        ),
    ]
