# Generated by Django 4.1 on 2022-10-17 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ferdolt', '0007_create_default_dbms_versions'),
        ('groups', '0002_alter_grouptabletable_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ferdolt.server')),
            ],
        ),
    ]
