# Generated by Django 4.1 on 2022-09-02 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_remove_groupdatabase_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupcolumn',
            name='column',
        ),
        migrations.RemoveField(
            model_name='grouptable',
            name='table',
        ),
    ]
