# Generated by Django 4.1 on 2022-09-02 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ferdolt', '0017_modify_database_schema_table_and_column_names_to_lowercase'),
        ('groups', '0003_remove_groupcolumn_column_remove_grouptable_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcolumn',
            name='data_type',
            field=models.CharField(default='int', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupdatabase',
            name='database',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ferdolt.database'),
        ),
        migrations.CreateModel(
            name='GroupColumnColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferdolt.column')),
                ('group_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.groupcolumn')),
            ],
        ),
    ]
