# Generated by Django 4.1 on 2022-10-19 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_groupserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupextraction',
            name='source_server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.groupserver'),
        ),
    ]
