# Generated by Django 4.1 on 2022-10-19 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_groupextraction_source_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupServerSynchronization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_applied', models.BooleanField(default=False)),
                ('time_applied', models.DateTimeField(null=True)),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('group_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.groupserver')),
            ],
        ),
    ]
