# Generated by Django 4.1 on 2022-09-02 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_groupcolumn_is_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptable',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='groups.group'),
        ),
    ]
