# Generated by Django 4.1 on 2022-10-19 22:38

from django.db import migrations, models
import groups.models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_groupserversynchronization'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupextraction',
            name='code',
            field=models.CharField(default=groups.models.generate_random_encryption_code, max_length=10),
        ),
    ]
