# Generated by Django 4.1 on 2022-10-19 22:53

from django.db import migrations

def set_group_created_by_to_default_server(apps, schema_editor):
    Group = apps.get_model("groups", "Group")
    Server = apps.get_model("ferdolt", "Server")

    # get the default server from the database
    server = Server.objects.filter(name='default').first()

    if server:
        for group in Group.objects.filter(created_by__isnull=True):
            group.created_by = server
            group.save()

class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_set_groupextraction_codes'),
    ]

    operations = [
        migrations.RunPython(
            set_group_created_by_to_default_server, 
            reverse_code=migrations.RunPython.noop
        )
    ]
