# Generated by Django 4.1 on 2022-09-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_set_group_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
