# Generated by Django 4.1 on 2022-09-04 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_alter_group_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupextraction',
            name='source_database',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.groupdatabase'),
        ),
        migrations.CreateModel(
            name='GroupDatabaseSynchronization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_applied', models.BooleanField(default=False)),
                ('time_applied', models.DateTimeField(null=True)),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.groupextraction')),
                ('group_database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.groupdatabase')),
            ],
        ),
    ]
