# Generated by Django 4.1 on 2022-10-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_set_group_created_by_to_default_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupserver',
            name='can_read',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='groupserver',
            name='can_write',
            field=models.BooleanField(default=True),
        ),
    ]
