# Generated by Django 4.1 on 2022-09-04 14:27

from django.db import migrations
from django.db.models import Q

def create_groupdatabase_synchronizations(apps, schema_editor):
    GroupExtraction = apps.get_model("groups", "GroupExtraction")
    GroupDatabaseSynchronization = apps.get_model("groups", "GroupDatabaseSynchronization")
    
    for extraction in GroupExtraction.objects.all():
        group_databases = extraction.group.groupdatabase_set.filter( 
            ~Q(id__in=extraction.groupdatabasesynchronization_set
            .values("group_database__id")
            )
        )

        for group_database in group_databases:
            GroupDatabaseSynchronization.objects.create( 
                group_database=group_database, 
                extraction=extraction
            )

class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_alter_groupextraction_source_database_and_more'),
    ]

    operations = [
        migrations.RunPython( create_groupdatabase_synchronizations, 
        migrations.RunPython.noop )
    ]
