# Generated by Django 4.1 on 2022-09-05 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ferdolt', '0017_modify_database_schema_table_and_column_names_to_lowercase'),
        ('groups', '0011_create_groupdatabase_synchronizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptable',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ferdolt.table'),
        ),
        migrations.AlterUniqueTogether(
            name='groupdatabasesynchronization',
            unique_together={('group_database', 'extraction')},
        ),
    ]
