# Generated by Django 4.1 on 2022-09-05 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0013_set_grouptable_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouptable',
            name='table',
        ),
    ]
