# Generated by Django 4.1 on 2022-09-05 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ferdolt', '0017_modify_database_schema_table_and_column_names_to_lowercase'),
        ('groups', '0014_remove_grouptable_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTableTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.grouptable')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferdolt.table')),
            ],
        ),
    ]
