# Generated by Django 4.1 on 2022-09-05 08:12

import logging
from django.db import migrations

def create_grouptabletable_instances(apps, schema_editor):
    GroupTable = apps.get_model("groups", "GroupTable")
    Table = apps.get_model("ferdolt", "Table")
    GroupColumnColumn = apps.get_model("groups", "GroupColumnColumn")
    GroupTableTable = apps.get_model("groups", "GroupTableTable")

    for group_table in GroupTable.objects.all():
        tables = Table.objects.filter( 
            column__id__in=GroupColumnColumn.objects
            .filter( group_column__group_table=group_table )
            .values("column__id")
        ).distinct()

        for table in tables:
            GroupTableTable.objects.create(group_table=group_table, table=table)

class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0015_grouptabletable'),
    ]

    operations = [
        migrations.RunPython( create_grouptabletable_instances, 
        reverse_code=migrations.RunPython.noop )
    ]
