# Generated by Django 4.1 on 2022-09-07 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0016_create_grouptabletable_instances'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupdatabase',
            old_name='is_readable',
            new_name='can_read',
        ),
        migrations.RenameField(
            model_name='groupdatabase',
            old_name='is_writeable',
            new_name='can_write',
        ),
    ]
