# Generated by Django 4.1 on 2022-09-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0017_rename_is_readable_groupdatabase_can_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='fernet_key',
            field=models.TextField(null=True, unique=True),
        ),
    ]
