# Generated by Django 4.1 on 2022-09-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0020_alter_group_fernet_key_alter_group_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='create_missing_objects_from_sources',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupcolumn',
            name='character_maximum_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupcolumn',
            name='data_type',
            field=models.CharField(choices=[('datetime', 'Datetime'), ('date', 'Date'), ('int', 'Integer'), ('float', 'Float'), ('double', 'Double'), ('char', 'Character')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='groupcolumn',
            unique_together={('group_table', 'name')},
        ),
    ]
